const Data = [
    {
        ISBN: "1234567891234",
        author: 'John Smith',
        bookTitle: 'The Book title 1',
        price: 100,
        numOfPages: 230,
        category: "action",
        rate: 5,
        cover: "https://vitaldigital.us/wp-content/uploads/2017/11/book-placeholder-small.png",
    },
    {
        ISBN: "1234567891244",
        author: 'John Smith',
        bookTitle: 'The Book title 2',
        price: 100,
        numOfPages: 230,
        category: "action",
        rate: 5,
        cover: "https://vitaldigital.us/wp-content/uploads/2017/11/book-placeholder-small.png",
    },
    {
        ISBN: "1234567891364",
        author: 'John Smith',
        bookTitle: 'The Book title 3',
        price: 100,
        numOfPages: 230,
        category: "action",
        rate: 5,
        cover: "https://vitaldigital.us/wp-content/uploads/2017/11/book-placeholder-small.png",
    },
    {
        ISBN: "1234567891239",
        author: 'John Smith',
        bookTitle: 'The Book title 3',
        price: 100,
        numOfPages: 230,
        category: "action",
        rate: 5,
        cover: "https://vitaldigital.us/wp-content/uploads/2017/11/book-placeholder-small.png",
    },
    {
        ISBN: "1234567891237",
        author: 'John Smith',
        bookTitle: 'The Book title 4',
        price: 100,
        numOfPages: 230,
        category: "action",
        rate: 5,
        cover: "https://vitaldigital.us/wp-content/uploads/2017/11/book-placeholder-small.png",
    },
]
