const orders = [
  {
    userId: "dLw4T2VjsQNj6BBMJGUvzF58Aar1",
    userName: "Ahmed Mohamed",
    userEmail: "ahmed@gmail.com",
    userAvatar: "https://www.w3schools.com/howto/img_avatar.png",
    books: [
      {
        ISBN: "1234567891234",
        author: "John Smith",
        bookTitle: "The Book title 1",
        price: 100,
        numOfPages: 230,
        category: "action",
        rate: 5,
        cover:"https://vitaldigital.us/wp-content/uploads/2017/11/book-placeholder-small.png",
        quantity: 2,
      },
      {
        ISBN: "1234567891244",
        author: "John Smith",
        bookTitle: "The Book title 2",
        price: 100,
        numOfPages: 230,
        category: "action",
        rate: 5,
        cover:"https://vitaldigital.us/wp-content/uploads/2017/11/book-placeholder-small.png",
        quantity: 3,
      },
    ],
    numberOfBooks: 2,
    totalPrice: 500,
    orderDate: new Date(),
  },
  {
    userId: "dLw4T2VjsQNj6BBMJGUvzF58Aar1",
    userName: "Ahmed Mohamed",
    userEmail: "ahmed@gmail.com",
    userAvatar: "https://www.w3schools.com/howto/img_avatar.png",
    books: [
      {
        ISBN: "1234567891234",
        author: "John Smith",
        bookTitle: "The Book title 1",
        price: 100,
        numOfPages: 230,
        category: "action",
        rate: 5,
        cover:"https://vitaldigital.us/wp-content/uploads/2017/11/book-placeholder-small.png",
        quantity: 2,
      },
      {
        ISBN: "1234567891244",
        author: "John Smith",
        bookTitle: "The Book title 2",
        price: 100,
        numOfPages: 230,
        category: "action",
        rate: 5,
        cover:"https://vitaldigital.us/wp-content/uploads/2017/11/book-placeholder-small.png",
        quantity: 3,
      },
    ],
    numberOfBooks: 2,
    totalPrice: 500,
    orderDate: new Date(),
  },
  {
    userId: "dLw4T2VjsQNj6BBMJGUvzF58Aar1",
    userName: "Ahmed Mohamed",
    userEmail: "ahmed@gmail.com",
    userAvatar: "https://www.w3schools.com/howto/img_avatar.png",
    books: [
      {
        ISBN: "1234567891234",
        author: "John Smith",
        bookTitle: "The Book title 1",
        price: 100,
        numOfPages: 230,
        category: "action",
        rate: 5,
        cover:"https://vitaldigital.us/wp-content/uploads/2017/11/book-placeholder-small.png",
        quantity: 2,
      },
      {
        ISBN: "1234567891244",
        author: "John Smith",
        bookTitle: "The Book title 2",
        price: 100,
        numOfPages: 230,
        category: "action",
        rate: 5,
        cover:"https://vitaldigital.us/wp-content/uploads/2017/11/book-placeholder-small.png",
        quantity: 3,
      },
    ],
    numberOfBooks: 2,
    totalPrice: 500,
    orderDate: new Date(),
  },
];

orders;
